# More examples of Codefresh YAML can be found at
# https://codefresh.io/docs/docs/yaml-examples/examples/

version: "1.0"
# Stages can help you organize your steps in stages
stages:
  - "clone"
  - "build"
  - "test"

steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "dozzler555/cfresh"
    # CF_BRANCH value is auto set when pipeline is triggered
    # Learn more at codefresh.io/docs/docs/codefresh-yaml/variables/
    revision: "${{CF_BRANCH}}"
    git: "github"
    stage: "clone"

  test:
    title: Install dependencies
    image: dazz111/ubuntu-sdk:build
    commands:
      - apt install wget -y
      - wget https://raw.githubusercontent.com/dozzler555/sem/main/sem.sh
      - chmod a+x sem.sh
      - git config --global color.ui false
      - bash sem.sh

